-- Script para ejecutar todas las migraciones de soporte en orden
-- Ejecutar con: psql -d tu_base_de_datos -f 000_run_all.sql

\echo 'Ejecutando migraciones de soporte...'

\i 001_support_agents.sql
\i 002_support_agent_sessions.sql
\i 003_support_agent_settings.sql
\i 004_support_agent_schedule.sql
\i 005_support_agent_breaks.sql
\i 006_support_agent_vacations.sql
\i 007_support_tickets.sql
\i 008_ticket_messages.sql
\i 009_ticket_attachments.sql
\i 010_ticket_internal_notes.sql
\i 011_ticket_history.sql
\i 012_ticket_collaborators.sql
\i 013_ticket_tags.sql
\i 014_ticket_merges.sql
\i 015_ticket_transfers.sql
\i 016_ticket_escalations.sql
\i 017_live_chat_sessions.sql
\i 018_live_chat_messages.sql
\i 019_live_chat_attachments.sql
\i 020_live_chat_notes.sql
\i 021_live_chat_transfers.sql
\i 022_chat_queue.sql
\i 023_sla_policies.sql
\i 024_sla_breaches.sql
\i 025_ticket_queue_priority.sql
\i 026_faqs.sql
\i 027_faq_categories.sql
\i 028_faq_feedback.sql
\i 029_support_templates.sql
\i 030_template_categories.sql
\i 031_agent_template_favorites.sql
\i 032_template_usage_log.sql
\i 033_canned_responses.sql
\i 034_quick_replies.sql
\i 035_knowledge_categories.sql
\i 036_knowledge_articles.sql
\i 037_knowledge_article_tags.sql
\i 038_knowledge_related_articles.sql
\i 039_knowledge_article_views.sql
\i 040_support_macros.sql
\i 041_macro_actions.sql
\i 042_macro_usage_log.sql
\i 043_agent_personal_notes.sql
\i 044_user_notes_by_agent.sql
\i 045_ticket_ratings.sql
\i 046_chat_ratings.sql
\i 047_rating_requests.sql
\i 048_internal_chat_rooms.sql
\i 049_internal_chat_members.sql
\i 050_internal_chat_messages.sql
\i 051_internal_chat_attachments.sql
\i 052_internal_chat_reactions.sql
\i 053_internal_chat_mentions.sql
\i 054_internal_chat_read_status.sql
\i 055_agent_notifications.sql
\i 056_agent_notification_preferences.sql
\i 057_agent_daily_stats.sql
\i 058_agent_performance_metrics.sql
\i 059_support_reports.sql
\i 060_scheduled_reports.sql
\i 061_ticket_category_stats.sql
\i 062_hourly_ticket_distribution.sql
\i 063_agent_trusted_devices.sql
\i 064_agent_login_history.sql
\i 065_agent_two_factor.sql
\i 066_agent_security_questions.sql
\i 067_agent_api_tokens.sql
\i 068_agent_webhooks.sql
\i 069_webhook_logs.sql
\i 070_agent_activity_logs.sql
\i 071_agent_status_history.sql
\i 072_agent_password_history.sql
\i 073_search_index.sql
\i 074_search_history.sql
\i 075_keyboard_shortcuts.sql
\i 076_default_shortcuts.sql
\i 077_available_tags.sql
\i 078_support_video_calls.sql
\i 079_language_detection_log.sql
\i 080_ai_response_suggestions.sql
\i 081_support_roles.sql
\i 082_agent_roles.sql
\i 083_support_permissions.sql
\i 084_auto_assignment_rules.sql
\i 085_agent_workload.sql
\i 086_data_exports.sql
\i 087_ticket_categories.sql
\i 088_csat_surveys.sql
\i 089_nps_scores.sql
\i 090_support_announcements.sql
\i 091_announcement_reads.sql
\i 092_chat_typing_status.sql
\i 093_pinned_internal_messages.sql
\i 094_pinned_ticket_notes.sql
\i 095_data_imports.sql
\i 096_chat_quick_replies.sql
\i 097_agent_quick_reply_favorites.sql
\i 098_live_chat_agent_notes.sql
\i 099_emoji_picker_history.sql
\i 100_message_reactions.sql
\i 101_internal_direct_contacts.sql
\i 102_internal_direct_messages.sql
\i 103_saved_ticket_filters.sql
\i 104_saved_queue_filters.sql
\i 105_bulk_action_history.sql
\i 106_agent_toast_preferences.sql
\i 107_realtime_notifications_queue.sql
\i 108_dashboard_widgets.sql
\i 109_dashboard_stats_cache.sql
\i 110_system_activity_feed.sql
\i 111_agent_activity_feed_reads.sql

\echo 'Migraciones de soporte completadas!'
